-- ====================================================================================
-- SUCHARU PRO COMMERCIAL PRINTING ERP
-- FORM 02 — VISUAL DESIGN STUDIO SEMANTIC PROPERTY GAP REPAIR MIGRATION
-- ====================================================================================

ALTER TABLE visual_design_configurations
ADD COLUMN IF NOT EXISTS image_area_dp INT NOT NULL DEFAULT 160,
ADD COLUMN IF NOT EXISTS content_area_padding_dp INT NOT NULL DEFAULT 12,
ADD COLUMN IF NOT EXISTS section_height_dp INT NOT NULL DEFAULT 480,
ADD COLUMN IF NOT EXISTS shadow_spread_dp INT NOT NULL DEFAULT 2,
ADD COLUMN IF NOT EXISTS margin_top_dp INT NOT NULL DEFAULT 8,
ADD COLUMN IF NOT EXISTS margin_bottom_dp INT NOT NULL DEFAULT 8,
ADD COLUMN IF NOT EXISTS font_style VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
ADD COLUMN IF NOT EXISTS letter_spacing_sp FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS line_height_sp INT NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS cta_button_size_dp INT NOT NULL DEFAULT 44,
ADD COLUMN IF NOT EXISTS cta_action_type VARCHAR(50) NOT NULL DEFAULT 'CHECKOUT',
ADD COLUMN IF NOT EXISTS cta_icon_name VARCHAR(50) NOT NULL DEFAULT 'SHOPPING_BAG',
ADD COLUMN IF NOT EXISTS background_image_uri VARCHAR(500);
