package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Accounts Receivable report (Module 09 Step 09).
 *
 * Reuses canonical CustomerReceivable data (Step 02).
 * Does NOT duplicate settlement calculations — reads from CustomerReceivable.outstandingAmount.
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class AccountsReceivableReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val totalReceivable: Money,
    val totalCollected: Money,
    val totalOutstanding: Money,
    val totalOverdue: Money,
    val overdueCount: Int,
    val agingBuckets: ReceivableAgingBucketSummary,
    val lines: List<ReceivableReportLine> = emptyList(),
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}

data class ReceivableAgingBucketSummary(
    val current: Money = Money.ZERO,
    val overdue1To30: Money = Money.ZERO,
    val overdue31To60: Money = Money.ZERO,
    val overdue61To90: Money = Money.ZERO,
    val overdue90Plus: Money = Money.ZERO
)

data class ReceivableReportLine(
    val receivableId: String,
    val receivableNo: String,
    val customerId: String,
    val customerName: String,
    val originalAmount: Money,
    val settledAmount: Money,
    val outstandingAmount: Money,
    val dueDate: Long,
    val status: CustomerReceivableStatus,
    val agingBucket: ReceivableAgingBucket
)
