package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Accounts Payable report (Module 09 Step 09).
 *
 * Reuses canonical VendorPayable data (Step 04).
 * Does NOT duplicate settlement calculations — reads from VendorPayable.outstandingAmount.
 *
 * Aging buckets: CURRENT, 1–30, 31–60, 61–90, 90+
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class AccountsPayableReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val totalPayable: Money,
    val totalSettled: Money,
    val totalOutstanding: Money,
    val totalOverdue: Money,
    val overdueCount: Int,
    val agingBuckets: PayableAgingBucketSummary,
    val lines: List<PayableReportLine> = emptyList(),
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}

data class PayableAgingBucketSummary(
    val current: Money = Money.ZERO,
    val overdue1To30: Money = Money.ZERO,
    val overdue31To60: Money = Money.ZERO,
    val overdue61To90: Money = Money.ZERO,
    val overdue90Plus: Money = Money.ZERO
)

data class PayableReportLine(
    val payableId: String,
    val payableNo: String,
    val vendorId: String,
    val vendorName: String,
    val originalAmount: Money,
    val settledAmount: Money,
    val outstandingAmount: Money,
    val dueDate: Long,
    val status: VendorPayableStatus,
    val agingBucket: VendorPayableAgingBucket
)
