package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Canonical Balance Sheet (Statement of Financial Position) report (Module 09 Step 09).
 *
 * Invariant: Total Assets = Total Liabilities + Total Equity
 *
 * If the equation does not balance:
 * - [isBalanced] = false
 * - [equationVariance] exposes the discrepancy
 * - status = CONTROL_EXCEPTION
 * - DO NOT silently correct
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class BalanceSheetReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    /** Asset lines: Cash, Bank, Receivables, Other Assets */
    val assetLines: List<FinancialReportLine>,
    /** Liability lines: Payables, Other Liabilities */
    val liabilityLines: List<FinancialReportLine>,
    /** Equity lines: Retained earnings, current period result */
    val equityLines: List<FinancialReportLine>,
    val totalAssets: Money,
    val totalLiabilities: Money,
    val totalEquity: Money,
    /** Variance = totalAssets - (totalLiabilities + totalEquity). Zero = balanced. */
    val equationVariance: Money,
    val isBalanced: Boolean = equationVariance.isZero(),
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}
