package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Cash Flow Summary report based on canonical posted financial transactions (Module 09 Step 09).
 *
 * Classification is based on what the existing account/reference architecture deterministically supports:
 * - Cash In: Customer receipts, other inflows
 * - Cash Out: Supplier payments, expenses, refunds paid
 * - Net Cash Movement: Cash In - Cash Out
 *
 * Reconciliation invariant:
 * Opening Cash + Net Cash Movement = Closing Cash
 *
 * If not balanced: [isReconciled] = false, [reconciliationVariance] is exposed.
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class CashFlowReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val openingCash: Money,
    val cashInLines: List<FinancialReportLine>,
    val cashOutLines: List<FinancialReportLine>,
    val totalCashIn: Money,
    val totalCashOut: Money,
    val netCashMovement: Money,
    val closingCash: Money,
    /** Variance = (openingCash + netCashMovement) - closingCash. Zero = reconciled. */
    val reconciliationVariance: Money,
    val isReconciled: Boolean = reconciliationVariance.isZero(),
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}
