package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Customer Payment Report result (Module 09 Step 09).
 *
 * Derives from canonical CustomerPayment records (Step 03).
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class CustomerPaymentReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val totalPayments: Money,
    val postedPayments: Money,
    val pendingPayments: Money,
    val cancelledPayments: Money,
    val totalReceiptsCount: Int,
    val paymentMethodBreakdown: List<CustomerPaymentMethodBreakdown> = emptyList(),
    val customerCollections: List<CustomerCollectionSummary> = emptyList(),
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}

data class CustomerPaymentMethodBreakdown(
    val paymentMethod: CustomerPaymentMethod,
    val totalAmount: Money,
    val paymentCount: Int,
    val percentageOfTotal: Double = 0.0
)

data class CustomerCollectionSummary(
    val customerId: String,
    val customerName: String,
    val totalCollected: Money,
    val paymentCount: Int
)
