package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Expense Analysis report (Module 09 Step 09).
 *
 * Reuses canonical Expense data (Step 06).
 * Does NOT recalculate expense truth independently.
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class ExpenseAnalysisReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val totalExpenses: Money,
    val approvedExpenses: Money,
    val postedExpenses: Money,
    val pendingExpenses: Money,
    val categoryBreakdown: List<ExpenseCategoryBreakdown>,
    val paymentMethodBreakdown: List<ExpensePaymentMethodBreakdown>,
    val topCategories: List<ExpenseCategoryBreakdown>,
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}


data class ExpensePaymentMethodBreakdown(
    val paymentMethod: ExpensePaymentMethod,
    val totalAmount: Money,
    val expenseCount: Int
)
