package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Immutable audit snapshot of a generated financial report (Module 09 Step 09).
 *
 * A snapshot represents the financial state at its generation/closing boundary.
 * Historical snapshot values MUST NOT change due to subsequent transactions.
 *
 * Idempotency: Same (projectId + reportType + periodKey + snapshotRequestId)
 * must not generate duplicate snapshots.
 *
 * [snapshotHash] is a SHA-256 digest of the canonical report totals + period + projectId.
 */
data class FinancialReportSnapshot(
    val snapshotId: String,
    val snapshotRequestId: String,
    val projectId: String,
    val reportType: FinancialReportType,
    val periodLabel: String,
    val startDate: Long,
    val endDate: Long,
    val totalRevenue: Money = Money.ZERO,
    val totalExpenses: Money = Money.ZERO,
    val netProfit: Money = Money.ZERO,
    val totalReceivable: Money = Money.ZERO,
    val totalPayable: Money = Money.ZERO,
    val cashPosition: Money = Money.ZERO,
    val bankPosition: Money = Money.ZERO,
    val isLedgerBalanced: Boolean = false,
    val isBalanceSheetBalanced: Boolean = false,
    val isTrialBalanced: Boolean = false,
    val reconciliationStatus: FinancialReconciliationStatus = FinancialReconciliationStatus.DRAFT,
    val closingPeriodStatus: AccountingPeriodStatus = AccountingPeriodStatus.OPEN,
    val sourcePeriodIds: List<String> = emptyList(),
    val controlExceptions: List<String> = emptyList(),
    val snapshotHash: String,
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String,
    val version: Int = 1
) {
    init {
        require(snapshotId.isNotBlank()) { "Snapshot ID cannot be blank." }
        require(snapshotRequestId.isNotBlank()) { "Snapshot request ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(periodLabel.isNotBlank()) { "Period label cannot be blank." }
        require(snapshotHash.isNotBlank()) { "Snapshot hash cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
        require(startDate > 0) { "Start date must be positive." }
        require(endDate >= startDate) { "End date cannot precede start date." }
        require(version > 0) { "Version must be positive." }
    }
}
