package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money
import java.math.BigDecimal
import java.math.RoundingMode

/**
 * Financial KPI summary for management analytics (Module 09 Step 09).
 *
 * Each KPI specifies:
 * - formula source
 * - currency where applicable
 * - calculation timestamp
 * - null if required source data is unavailable (never NaN, never Infinity)
 *
 * All percentage values are in [0.0, 100.0] range unless ratio exceeds bounds.
 * A null value means "not calculable" — always expose null rather than a misleading zero.
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class FinancialKpiSummary(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    /** Total revenue in period */
    val totalRevenue: Money,
    /** Total expenses in period */
    val totalExpenses: Money,
    /** Net profit in period */
    val netProfit: Money,
    /** Cash position (cash in hand) */
    val cashPosition: Money,
    /** Bank position */
    val bankPosition: Money,
    /** Total outstanding receivable */
    val totalReceivableOutstanding: Money,
    /** Total outstanding payable */
    val totalPayableOutstanding: Money,
    /** Total collected in period */
    val totalCollected: Money,
    /** Total supplier payments in period */
    val totalSupplierPayments: Money,
    /** Overdue receivable */
    val totalOverdueReceivable: Money,
    /** Overdue payable */
    val totalOverduePayable: Money,
    /** Collection Rate = (totalCollected / totalRevenue) * 100. Null if totalRevenue is zero. */
    val collectionRatePercent: Double?,
    /** Net Profit Margin = (netProfit / totalRevenue) * 100. Null if totalRevenue is zero. */
    val netProfitMarginPercent: Double?,
    /** Expense Ratio = (totalExpenses / totalRevenue) * 100. Null if totalRevenue is zero. */
    val expenseRatioPercent: Double?,
    /** Overdue Receivable Ratio = (totalOverdueReceivable / totalReceivableOutstanding) * 100. Null if zero. */
    val overdueReceivableRatioPercent: Double?,
    /** Overdue Payable Ratio = (totalOverduePayable / totalPayableOutstanding) * 100. Null if zero. */
    val overduePayableRatioPercent: Double?,
    val controlExceptions: List<String> = emptyList(),
    val calculatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(calculatedAt > 0) { "Calculated timestamp must be positive." }
        // Validate that no percentage is NaN or Infinity
        listOfNotNull(collectionRatePercent, netProfitMarginPercent, expenseRatioPercent,
            overdueReceivableRatioPercent, overduePayableRatioPercent).forEach { pct ->
            require(pct.isFinite()) { "KPI percentage values must be finite. Found: $pct" }
        }
    }
}
