package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Result of a period-over-period financial comparison (Module 09 Step 09).
 *
 * Supports: Month vs Month, Quarter vs Quarter, Year vs Year, Custom Period A vs Period B.
 *
 * Zero-denominator handling:
 * - If Period A value is zero: percentageChange = null (not calculable)
 * - Never returns NaN or Infinity
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class FinancialComparisonResult(
    val reportId: String,
    val projectId: String,
    val status: FinancialReportStatus,
    val periodALabel: String,
    val periodBLabel: String,
    // Revenue
    val revenueA: Money,
    val revenueB: Money,
    val revenueAbsoluteChange: Money,
    val revenuePercentageChange: Double?,
    // Expenses
    val expensesA: Money,
    val expensesB: Money,
    val expensesAbsoluteChange: Money,
    val expensesPercentageChange: Double?,
    // Net Profit
    val profitA: Money,
    val profitB: Money,
    val profitAbsoluteChange: Money,
    val profitPercentageChange: Double?,
    // Collections
    val collectionsA: Money,
    val collectionsB: Money,
    val collectionsAbsoluteChange: Money,
    val collectionsPercentageChange: Double?,
    // Supplier Payments
    val supplierPaymentsA: Money,
    val supplierPaymentsB: Money,
    val supplierPaymentsAbsoluteChange: Money,
    val supplierPaymentsPercentageChange: Double?,
    // Receivables
    val receivablesA: Money,
    val receivablesB: Money,
    val receivablesAbsoluteChange: Money,
    val receivablesPercentageChange: Double?,
    // Payables
    val payablesA: Money,
    val payablesB: Money,
    val payablesAbsoluteChange: Money,
    val payablesPercentageChange: Double?,
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(periodALabel.isNotBlank()) { "Period A label cannot be blank." }
        require(periodBLabel.isNotBlank()) { "Period B label cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
        // Validate finite percentages
        listOfNotNull(revenuePercentageChange, expensesPercentageChange, profitPercentageChange,
            collectionsPercentageChange, supplierPaymentsPercentageChange,
            receivablesPercentageChange, payablesPercentageChange).forEach { pct ->
            require(pct.isFinite()) { "Comparison percentage values must be finite. Found: $pct" }
        }
    }
}
