package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Lightweight summary header for a generated financial report (Module 09 Step 09).
 *
 * Used for report list views and report index screens.
 * Does not contain the full report body to avoid memory overhead.
 */
data class FinancialReportSummary(
    val reportId: String,
    val projectId: String,
    val reportType: FinancialReportType,
    val reportPeriod: FinancialReportPeriod,
    val status: FinancialReportStatus,
    val generatedAt: Long,
    val generatedBy: String,
    val primaryTotal: Money = Money.ZERO,
    val controlExceptions: List<String> = emptyList(),
    val snapshotId: String? = null
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}
