package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Immutable management analytics snapshot with SHA-256 integrity hash (Module 09 Step 10).
 */
data class FinancialAnalyticsSnapshot(
    val snapshotId: String,
    val snapshotRequestId: String,
    val projectId: String,
    val periodLabel: String,
    val healthScore: Int,
    val healthStatus: FinancialHealthStatus,
    val totalRevenue: Money,
    val totalExpenses: Money,
    val netProfit: Money,
    val cashPosition: Money,
    val totalReceivables: Money,
    val totalPayables: Money,
    val criticalRiskCount: Int,
    val anomalyCount: Int,
    val governanceStatus: FinancialGovernanceStatus,
    val snapshotHash: String,
    val generatedBy: String,
    val generatedAt: Long = System.currentTimeMillis()
) {
    init {
        require(snapshotId.isNotBlank()) { "Snapshot ID cannot be blank." }
        require(snapshotRequestId.isNotBlank()) { "Snapshot request ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(snapshotHash.isNotBlank()) { "Snapshot hash cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
    }
}
