package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Financial Adjustment & Credit/Debit Note Report (Module 09 Step 09).
 *
 * Derives from canonical FinancialAdjustment, CustomerCreditNote, VendorDebitNote, CustomerRefund records (Step 07).
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class FinancialAdjustmentReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val totalAdjustmentsCount: Int,
    val totalCreditNotesAmount: Money,
    val totalDebitNotesAmount: Money,
    val totalRefundsAmount: Money,
    val totalInternalAdjustmentsAmount: Money,
    val totalWriteOffsAmount: Money,
    val postedAmount: Money,
    val pendingAmount: Money,
    val cancelledAmount: Money,
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}
