package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * General Ledger report with chronological ledger entries and running balance (Module 09 Step 09).
 *
 * Each entry corresponds to a posted FinancialLedgerEntry.
 * Running balance is deterministic — sorted by entryDate, then entryNo.
 *
 * FinancialLedgerEntry data is NEVER mutated during report generation.
 * Pagination supported via [filter.page] and [filter.pageSize].
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class GeneralLedgerReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val entries: List<GeneralLedgerEntry>,
    val openingBalance: Money,
    val closingBalance: Money,
    val totalDebitPosted: Money,
    val totalCreditPosted: Money,
    val totalEntries: Int,
    val currentPage: Int,
    val totalPages: Int,
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}

/**
 * A single chronological entry in the General Ledger report (Module 09 Step 09).
 */
data class GeneralLedgerEntry(
    val entryId: String,
    val transactionId: String,
    val transactionDate: Long,
    val entryDate: Long,
    val accountHead: String,
    val referenceType: FinancialReferenceType,
    val referenceId: String,
    val narration: String,
    val debit: Money,
    val credit: Money,
    /** Running balance up to and including this entry (cumulative). */
    val runningBalance: Money
) {
    init {
        require(entryId.isNotBlank()) { "Entry ID cannot be blank." }
        require(transactionId.isNotBlank()) { "Transaction ID cannot be blank." }
        require(accountHead.isNotBlank()) { "Account head cannot be blank." }
        require(referenceId.isNotBlank()) { "Reference ID cannot be blank." }
        require(narration.isNotBlank()) { "Narration cannot be blank." }
    }
}
