package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Canonical Profit & Loss (Income Statement) report result (Module 09 Step 09).
 *
 * Derives from:
 * - Revenue: FinancialTransaction (SALE, RECEIPT) + posted FinancialAdjustment income effects
 * - Expenses: Expense (POSTED) + SupplierPayment effects
 * - Adjustments: CustomerCreditNote, VendorDebitNote where applicable
 *
 * Net Profit = Total Revenue - Total Expenses (with applicable adjustments)
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class ProfitLossReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    /** Revenue lines: sales, other income, positive adjustments */
    val revenueLines: List<FinancialReportLine>,
    /** Expense lines: operating expenses, other expenses by category */
    val expenseLines: List<FinancialReportLine>,
    /** Adjustment lines: credit notes, refunds, etc. */
    val adjustmentLines: List<FinancialReportLine>,
    val totalRevenue: Money,
    val totalExpenses: Money,
    val totalAdjustments: Money,
    /** Net Profit = totalRevenue - totalExpenses + adjustmentEffect */
    val netProfit: Money,
    val isProfit: Boolean = netProfit >= Money.ZERO,
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}
