package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Supplier Payment Report result (Module 09 Step 09).
 *
 * Derives from canonical SupplierPayment records (Step 05).
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class SupplierPaymentReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val totalPayments: Money,
    val postedPayments: Money,
    val pendingPayments: Money,
    val cancelledPayments: Money,
    val totalSettledAmount: Money,
    val paymentMethodBreakdown: List<SupplierPaymentMethodBreakdown> = emptyList(),
    val vendorPayments: List<VendorPaymentSummary> = emptyList(),
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}

data class SupplierPaymentMethodBreakdown(
    val paymentMethod: SupplierPaymentMethod,
    val totalAmount: Money,
    val paymentCount: Int,
    val percentageOfTotal: Double = 0.0
)

data class VendorPaymentSummary(
    val vendorId: String,
    val vendorName: String,
    val totalPaid: Money,
    val paymentCount: Int
)
