package com.sucharu.sucharupro.domain.model.finance

import com.sucharu.sucharupro.domain.model.common.Money

/**
 * Canonical Trial Balance report from FinancialLedgerEntry data (Module 09 Step 09).
 *
 * Each line represents an account head with its total debits, credits, and net balance.
 *
 * Control invariant: Total Debit == Total Credit
 *
 * If not balanced:
 * - [isBalanced] = false
 * - [difference] is exposed
 * - status = CONTROL_EXCEPTION
 * - Ledger data is NEVER altered
 *
 * IMMUTABLE. Must not be mutated after generation.
 */
data class TrialBalanceReport(
    val reportId: String,
    val projectId: String,
    val filter: FinancialReportFilter,
    val status: FinancialReportStatus,
    val lines: List<TrialBalanceLine>,
    val totalDebit: Money,
    val totalCredit: Money,
    /** Difference = totalDebit - totalCredit. Zero = balanced. */
    val difference: Money,
    val isBalanced: Boolean = difference.isZero(),
    val controlExceptions: List<String> = emptyList(),
    val generatedAt: Long = System.currentTimeMillis(),
    val generatedBy: String
) {
    init {
        require(reportId.isNotBlank()) { "Report ID cannot be blank." }
        require(projectId.isNotBlank()) { "Project ID cannot be blank." }
        require(generatedBy.isNotBlank()) { "Generated by cannot be blank." }
        require(generatedAt > 0) { "Generated timestamp must be positive." }
    }
}

/**
 * A single account line in the Trial Balance (Module 09 Step 09).
 */
data class TrialBalanceLine(
    val accountHead: String,
    val accountHeadName: String,
    val totalDebit: Money,
    val totalCredit: Money,
    /** Net balance = totalDebit - totalCredit (can be negative for credit-side accounts) */
    val netBalance: Money = totalDebit - totalCredit
) {
    init {
        require(accountHead.isNotBlank()) { "Account head cannot be blank." }
        require(accountHeadName.isNotBlank()) { "Account head name cannot be blank." }
    }
}
