package com.sucharu.sucharupro.ui.features.profitability.product

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.sucharu.sucharupro.data.api.model.profitability.ProductProfitabilitySnapshotDto

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ProductProfitabilityDetailsScreen(
    snapshot: ProductProfitabilitySnapshotDto?,
    onBackClick: () -> Unit = {}
) {
    val darkNavyBg = Color(0xFF0B132B)
    val cardBg = Color(0xFF1C2541)
    val accentCyan = Color(0xFF9ECAFF)
    val successGreen = Color(0xFF4EBA6F)
    val warningOrange = Color(0xFFFFB74D)
    val errorRed = Color(0xFFFF6B6B)

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text("Product Profitability Details", fontWeight = FontWeight.Bold, color = Color.White, fontSize = 18.sp)
                        Text("${snapshot?.productName ?: "Product"} • ID: ${snapshot?.productId ?: "N/A"}", fontSize = 12.sp, color = Color.LightGray)
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBackClick) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = Color.White)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = darkNavyBg)
            )
        },
        containerColor = darkNavyBg
    ) { paddingValues ->
        if (snapshot == null) {
            Box(modifier = Modifier.fillMaxSize().padding(paddingValues), contentAlignment = Alignment.Center) {
                Text("No Snapshot Available", color = Color.Gray)
            }
        } else {
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(paddingValues)
                    .padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(14.dp)
            ) {
                // Snapshot Meta Card
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        colors = CardDefaults.cardColors(containerColor = cardBg),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text("Snapshot Metadata", color = accentCyan, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                            DetailRow("Snapshot ID", snapshot.snapshotId)
                            DetailRow("SKU", snapshot.sku ?: "N/A")
                            DetailRow("Edition", snapshot.editionId ?: "Standard")
                            DetailRow("Version", snapshot.versionId ?: "v1.0")
                            DetailRow("Period", snapshot.periodId ?: "Current")
                            DetailRow("Customer", snapshot.customerId ?: "All Customers")
                            DetailRow("Version Engine", snapshot.calculationVersion)
                            DetailRow("Generated By", snapshot.generatedBy)
                        }
                    }
                }

                // Financial Metrics Card
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        colors = CardDefaults.cardColors(containerColor = cardBg),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text("Financial Performance", color = accentCyan, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                            DetailRow("Recognized Revenue", "৳${snapshot.recognizedRevenue}")
                            DetailRow("Total Actual Cost", "৳${snapshot.totalActualCost}")
                            DetailRow("Gross Profit", "৳${snapshot.grossProfit}", if (snapshot.grossProfit.toDouble() >= 0) successGreen else errorRed)
                            DetailRow("Gross Margin", "${snapshot.grossMarginPercentage ?: "N/A"}%", accentCyan)
                            DetailRow("Classification", snapshot.profitabilityClassification)
                        }
                    }
                }

                // Variance & Integrity Card
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        colors = CardDefaults.cardColors(containerColor = cardBg),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text("Variance & Integrity Control", color = accentCyan, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                            DetailRow("Baseline Cost", "৳${snapshot.baselineCost ?: "N/A"}")
                            DetailRow("Cost Variance", "৳${snapshot.costVariance ?: "N/A"}")
                            DetailRow("Variance %", "${snapshot.costVariancePercentage ?: "N/A"}%")
                            DetailRow("Variance Status", snapshot.varianceClassification)
                            DetailRow("Source Integrity", snapshot.sourceIntegrityStatus)
                            DetailRow("Reconciliation Status", if (snapshot.isReconciled) "RECONCILED" else "UNRECONCILED", if (snapshot.isReconciled) successGreen else errorRed)
                            DetailRow("Integrity SHA-256", snapshot.integrityHash.take(16) + "...", Color.Gray)
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun DetailRow(label: String, value: String, valueColor: Color = Color.White) {
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(label, color = Color.Gray, fontSize = 13.sp)
        Text(value, color = valueColor, fontWeight = FontWeight.Medium, fontSize = 13.sp)
    }
}
